add_requires("plog")

target("logging")
  set_kind("static")
  set_languages("c++23")
  set_policy("check.auto_ignore_flags", false)
  set_toolchains("clang")
  set_warnings("all")
  add_cxxflags("-stdlib=libc++", "-fPIE")
  add_ldflags("-stdlib=libc++")
  add_files("*.cpp")
  add_includedirs("private")
  add_includedirs("public", { public = true })
  add_packages("plog")