# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
AS=/usr/bin/gcc-12
MXX=/usr/bin/gcc-12
CC=/usr/bin/gcc-12
MM=/usr/bin/gcc-12
CXX=/usr/bin/gcc-12

LD=/usr/bin/g++-12
AR=/usr/bin/ar
SH=/usr/bin/g++-12

