# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
CXX=/usr/bin/gcc-12
MXX=/usr/bin/gcc-12
AS=/usr/bin/gcc-12
CC=/usr/bin/gcc-12
MM=/usr/bin/gcc-12

LD=/usr/bin/g++-12
AR=/usr/bin/ar
SH=/usr/bin/g++-12


bonding_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -Ilib/spdlog/include -Ilib/structopt/include -Ilib/result/include -DNDEBUG
bonding_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -Ilib/spdlog/include -Ilib/structopt/include -Ilib/result/include -DNDEBUG
bonding_LDFLAGS=-m64 -s -lseccomp -lcap

default:  bonding

all:  bonding

.PHONY: default all  bonding

bonding: build/linux/x86_64/release/bonding
build/linux/x86_64/release/bonding: build/.objs/bonding/linux/x86_64/release/src/capabilities.cpp.o build/.objs/bonding/linux/x86_64/release/src/child.cpp.o build/.objs/bonding/linux/x86_64/release/src/cli.cpp.o build/.objs/bonding/linux/x86_64/release/src/config.cpp.o build/.objs/bonding/linux/x86_64/release/src/container.cpp.o build/.objs/bonding/linux/x86_64/release/src/error.cpp.o build/.objs/bonding/linux/x86_64/release/src/exec.cpp.o build/.objs/bonding/linux/x86_64/release/src/hostname.cpp.o build/.objs/bonding/linux/x86_64/release/src/ipc.cpp.o build/.objs/bonding/linux/x86_64/release/src/main.cpp.o build/.objs/bonding/linux/x86_64/release/src/mount.cpp.o build/.objs/bonding/linux/x86_64/release/src/namespace.cpp.o build/.objs/bonding/linux/x86_64/release/src/resource.cpp.o build/.objs/bonding/linux/x86_64/release/src/syscall.cpp.o
	@echo linking.release bonding
	@mkdir -p build/linux/x86_64/release
	$(VV)$(LD) -o build/linux/x86_64/release/bonding build/.objs/bonding/linux/x86_64/release/src/capabilities.cpp.o build/.objs/bonding/linux/x86_64/release/src/child.cpp.o build/.objs/bonding/linux/x86_64/release/src/cli.cpp.o build/.objs/bonding/linux/x86_64/release/src/config.cpp.o build/.objs/bonding/linux/x86_64/release/src/container.cpp.o build/.objs/bonding/linux/x86_64/release/src/error.cpp.o build/.objs/bonding/linux/x86_64/release/src/exec.cpp.o build/.objs/bonding/linux/x86_64/release/src/hostname.cpp.o build/.objs/bonding/linux/x86_64/release/src/ipc.cpp.o build/.objs/bonding/linux/x86_64/release/src/main.cpp.o build/.objs/bonding/linux/x86_64/release/src/mount.cpp.o build/.objs/bonding/linux/x86_64/release/src/namespace.cpp.o build/.objs/bonding/linux/x86_64/release/src/resource.cpp.o build/.objs/bonding/linux/x86_64/release/src/syscall.cpp.o $(bonding_LDFLAGS)

build/.objs/bonding/linux/x86_64/release/src/capabilities.cpp.o: src/capabilities.cpp
	@echo ccache compiling.release src/capabilities.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/capabilities.cpp.o src/capabilities.cpp

build/.objs/bonding/linux/x86_64/release/src/child.cpp.o: src/child.cpp
	@echo ccache compiling.release src/child.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/child.cpp.o src/child.cpp

build/.objs/bonding/linux/x86_64/release/src/cli.cpp.o: src/cli.cpp
	@echo ccache compiling.release src/cli.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/cli.cpp.o src/cli.cpp

build/.objs/bonding/linux/x86_64/release/src/config.cpp.o: src/config.cpp
	@echo ccache compiling.release src/config.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/config.cpp.o src/config.cpp

build/.objs/bonding/linux/x86_64/release/src/container.cpp.o: src/container.cpp
	@echo ccache compiling.release src/container.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/container.cpp.o src/container.cpp

build/.objs/bonding/linux/x86_64/release/src/error.cpp.o: src/error.cpp
	@echo ccache compiling.release src/error.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/error.cpp.o src/error.cpp

build/.objs/bonding/linux/x86_64/release/src/exec.cpp.o: src/exec.cpp
	@echo ccache compiling.release src/exec.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/exec.cpp.o src/exec.cpp

build/.objs/bonding/linux/x86_64/release/src/hostname.cpp.o: src/hostname.cpp
	@echo ccache compiling.release src/hostname.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/hostname.cpp.o src/hostname.cpp

build/.objs/bonding/linux/x86_64/release/src/ipc.cpp.o: src/ipc.cpp
	@echo ccache compiling.release src/ipc.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/ipc.cpp.o src/ipc.cpp

build/.objs/bonding/linux/x86_64/release/src/main.cpp.o: src/main.cpp
	@echo ccache compiling.release src/main.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/main.cpp.o src/main.cpp

build/.objs/bonding/linux/x86_64/release/src/mount.cpp.o: src/mount.cpp
	@echo ccache compiling.release src/mount.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/mount.cpp.o src/mount.cpp

build/.objs/bonding/linux/x86_64/release/src/namespace.cpp.o: src/namespace.cpp
	@echo ccache compiling.release src/namespace.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/namespace.cpp.o src/namespace.cpp

build/.objs/bonding/linux/x86_64/release/src/resource.cpp.o: src/resource.cpp
	@echo ccache compiling.release src/resource.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/resource.cpp.o src/resource.cpp

build/.objs/bonding/linux/x86_64/release/src/syscall.cpp.o: src/syscall.cpp
	@echo ccache compiling.release src/syscall.cpp
	@mkdir -p build/.objs/bonding/linux/x86_64/release/src
	$(VV)$(CXX) -c $(bonding_CXXFLAGS) -o build/.objs/bonding/linux/x86_64/release/src/syscall.cpp.o src/syscall.cpp

clean:  clean_bonding

clean_bonding: 
	@rm -rf build/linux/x86_64/release/bonding
	@rm -rf build/linux/x86_64/release/bonding.sym
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/capabilities.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/child.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/cli.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/config.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/container.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/error.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/exec.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/hostname.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/ipc.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/main.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/mount.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/namespace.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/resource.cpp.o
	@rm -rf build/.objs/bonding/linux/x86_64/release/src/syscall.cpp.o

